"use strict";

const C = {
  STARTING_HP: 20,
  STARTING_HAND_SIZE: 3,
  STARTING_MANA: 0,
  MANA_GAIN_PER_TURN: 1,
  MAX_MANA: 10,
  TURN_TIME_LIMIT_SECONDS: 45.0,
  MAX_HAND_SIZE: 7,
  MAX_BOARD_SIZE: 5,

  CARD_TYPE_SPELL: "spell",
  CARD_TYPE_UNIT: "unit",

  TARGET_NONE: "none",
  TARGET_FRIENDLY_PLAYER: "friendly_player",
  TARGET_ENEMY_PLAYER: "enemy_player",
  TARGET_ANY_ENEMY: "any_enemy",
  TARGET_ANY_FRIENDLY: "any_friendly",
  TARGET_ANY_UNIT: "any_unit",
  TARGET_ENEMY_UNIT: "enemy_unit",
  TARGET_FRIENDLY_UNIT: "friendly_unit",

  ACTION_NONE: "none",
  ACTION_SPELL: "spell",
  ACTION_UNIT_ATTACK: "unit_attack",
  ACTION_ABILITY: "ability",

  TRIGGER_BATTLECRY: "battlecry",
  TRIGGER_AURA: "aura",
  TRIGGER_ON_UNIT_PLAYED: "on_unit_played",
  TRIGGER_WHEN_KILLS: "when_kills",
  TRIGGER_WHEN_DESTROYED: "when_destroyed",
  TRIGGER_TURN_START: "turn_start",
  TRIGGER_ON_SPELL_PLAYED: "on_spell_played",
  TRIGGER_ON_ALLY_UNIT_ATTACK: "on_ally_unit_attack",
  TRIGGER_TURN_END: "turn_end",
  TRIGGER_WHEN_ATTACKED: "when_attacked",
  TRIGGER_ON_ALLY_UNIT_DAMAGED: "on_ally_unit_damaged",

  KEYWORD_RUSH: "rush",
  KEYWORD_HASTE: "haste",
  KEYWORD_TAUNT: "taunt",
  KEYWORD_UNTRICKABLE: "untrickable",
  KEYWORD_RICOCHET: "ricochet",
  KEYWORD_IMMOBILE: "immobile",
  KEYWORD_INVINCIBLE: "invincible",
  KEYWORD_DEADLY: "deadly",

  EFFECT_NONE: "none",
  EFFECT_DAMAGE: "damage",
  EFFECT_HEAL: "heal",
  EFFECT_DRAW: "draw",
  EFFECT_UNIT: "unit",
  EFFECT_DESTROY_UNIT: "destroy_unit",
  EFFECT_ADD_KEYWORD: "add_keyword",
  EFFECT_BUFF_DECK_TRAIT: "buff_deck_trait",
  EFFECT_HEAL_ALL_ALLIES_GAIN_MAX_HP: "heal_all_allies_gain_max_hp",
  EFFECT_REDUCE_ENEMY_MAX_HP_THEN_ADD_COPIES: "reduce_enemy_max_hp_then_add_copies",
  EFFECT_ADD_ZERO_COST_COPIES_OF_LAST_SPELL: "add_zero_cost_copies_of_last_spell",
  EFFECT_DRAW_RANDOM_TRAIT_FROM_DECK_INCREASE_COST: "draw_random_trait_from_deck_increase_cost",
  EFFECT_HAP_HAZARD: "hap_hazard",
  EFFECT_DAMAGE_BY_BOARD_TRAIT_COUNT: "damage_by_board_trait_count",
  EFFECT_ADD_KEYWORDS_TO_UNIT: "add_keywords_to_unit",
  EFFECT_RESURRECT_TRAIT_UNITS_FROM_GRAVEYARD: "resurrect_trait_units_from_graveyard",
  EFFECT_TEMPORARY_IMMOBILE_ALL_ENEMY_UNITS: "temporary_immobile_all_enemy_units",
  EFFECT_DESTROY_FRIENDLY_TRAIT_UNIT_COPY_TO_HAND_BUFF: "destroy_friendly_trait_unit_copy_to_hand_buff",
  EFFECT_RETURN_RANDOM_HAND_UNIT_DRAW_ANOTHER_TRAIT_UNIT: "return_random_hand_unit_draw_another_trait_unit",
  EFFECT_MASTERWORK_OF_ART: "masterwork_of_art",
  EFFECT_RUNIC_TUNING: "runic_tuning",
  EFFECT_LAMENTATION_OF_LIFE: "lamentation_of_life",
  EFFECT_INCANTATION_OF_MINSTREL: "incantation_of_minstrel",
  EFFECT_LIGHTNING_CEREMONY: "lightning_ceremony",
  EFFECT_SCAVENGE_COMMAND: "scavenge_command",
  EFFECT_DUEL_ON_SEA: "duel_on_sea",
  EFFECT_RIME_OF_THE_ANCIENT_MARINER: "rime_of_the_ancient_mariner",
  EFFECT_ENCOMPASSED_COMPASS: "encompassed_compass",
  EFFECT_STORM_AND_TIDES: "storm_and_tides",
  EFFECT_CALL_OF_OMEN: "call_of_omen",
  EFFECT_BUFF_ALL_ALLY_UNITS: "buff_all_ally_units",
  EFFECT_POETRY_OF_RESILIENCE: "poetry_of_resilience",
  EFFECT_CONVIVIAL_HUMMING: "convivial_humming",

  ABILITY_EFFECT_GAIN_MANA: "gain_mana",
  ABILITY_EFFECT_DAMAGE: "damage",
  ABILITY_EFFECT_BUFF_TRAIT: "buff_trait",
  ABILITY_EFFECT_GRANT_KEYWORDS_TO_TRAIT: "grant_keywords_to_trait",
  ABILITY_EFFECT_DRAW: "draw",
  ABILITY_EFFECT_BUFF_RANDOM_HAND_TRAIT: "buff_random_hand_trait",
  ABILITY_EFFECT_COPY_SELF_TO_HAND: "copy_self_to_hand",
  ABILITY_EFFECT_COPY_SELF_TO_BOARD: "copy_self_to_board",
  ABILITY_EFFECT_SPELL_DAMAGE_BONUS: "spell_damage_bonus",
  ABILITY_EFFECT_REDUCE_HAND_SPELL_COST: "reduce_hand_spell_cost",
  ABILITY_EFFECT_DRAW_RANDOM_SPELL_FROM_DECK: "draw_random_spell_from_deck",
  ABILITY_EFFECT_REMOVE_KEYWORDS_FROM_PLAYED_UNIT: "remove_keywords_from_played_unit",
  ABILITY_EFFECT_BURN_SPELL_FROM_HAND_THEN_BUFF_SELF: "burn_spell_from_hand_then_buff_self",
  ABILITY_EFFECT_ADD_COPIES_TO_DECK: "add_copies_to_deck",
  ABILITY_EFFECT_REDUCE_ENEMY_MAX_HP: "reduce_enemy_max_hp",
  ABILITY_EFFECT_LOSE_STATS_FOR_OTHER_ALLY_UNITS: "lose_stats_for_other_ally_units",
  ABILITY_EFFECT_BUFF_SELF: "buff_self",
  ABILITY_EFFECT_MODIFY_HAND_COST_BY_TRAIT: "modify_hand_cost_by_trait",
  ABILITY_EFFECT_BUFF_OTHER_FRIENDLY_TRAIT_UNITS: "buff_other_friendly_trait_units",
  ABILITY_EFFECT_DAMAGE_RANDOM_ENEMY_UNIT_OR_FACE: "damage_random_enemy_unit_or_face",
  ABILITY_EFFECT_SUMMON_CARDS: "summon_cards",
  ABILITY_EFFECT_DESTROY_LOWEST_HEALTH_ENEMY_UNIT: "destroy_lowest_health_enemy_unit",
  ABILITY_EFFECT_DESTROY_FRIENDLY_UNIT_GAIN_STATS: "destroy_friendly_unit_gain_stats",
  ABILITY_EFFECT_DAMAGE_ENEMY_LEADER_ON_ALLY_ATTACK: "damage_enemy_leader_on_ally_attack",
  ABILITY_EFFECT_REMOVE_IMMOBILE_SET_ATTACK_FOR_TRAIT: "remove_immobile_set_attack_for_trait",
  ABILITY_EFFECT_RETURN_RANDOM_HAND_TRAIT_CARD_THEN_DAMAGE_ALL_ENEMY_UNITS: "return_random_hand_trait_card_then_damage_all_enemy_units",
  ABILITY_EFFECT_DESTROY_ENEMY_UNIT_AND_HEAL_LEADER: "destroy_enemy_unit_and_heal_leader",
  ABILITY_EFFECT_GAIN_ATTACK_FROM_ALLIED_TRAIT_ATTACK_TOTAL: "gain_attack_from_allied_trait_attack_total",
  ABILITY_EFFECT_DRAW_CARD_THAT_COSTS_MORE: "draw_card_that_costs_more",
  ABILITY_EFFECT_DRAW_RANDOM_TRAIT_UNIT_FROM_DECK: "draw_random_trait_unit_from_deck",
  ABILITY_EFFECT_LOOK_TOP_DECK_KEEP_OR_BOTTOM: "look_top_deck_keep_or_bottom",
  ABILITY_EFFECT_ADD_CARD_TO_HAND: "add_card_to_hand",
  ABILITY_EFFECT_GAIN_TEMPORARY_KEYWORD: "gain_temporary_keyword",
  ABILITY_EFFECT_ADD_CARD_TO_HAND_IF_TRAIT_PLAYED_COUNT: "add_card_to_hand_if_trait_played_count",
  ABILITY_EFFECT_REMOVE_KEYWORD_THEN_BUFF_SELF: "remove_keyword_then_buff_self",
  ABILITY_EFFECT_SUMMON_THREE_KEYWORD_COPIES: "summon_three_keyword_copies",
  ABILITY_EFFECT_DESTROY_ALL_OTHER_UNITS_AND_FULL_HEAL_LEADER: "destroy_all_other_units_and_full_heal_leader",
  ABILITY_EFFECT_DAMAGE_PLAYED_UNIT: "damage_played_unit",
  ABILITY_EFFECT_BUFF_ATTACKER: "buff_attacker",
  ABILITY_EFFECT_HEAL_DAMAGED_ALLY_GADGET_AND_DAMAGE_ENEMY_LEADER: "heal_damaged_ally_gadget_and_damage_enemy_leader",

  TARGET_ALL_ENEMY_UNITS: "all_enemy_units",
  TARGET_FRIENDLY_UNITS_WITH_TRAIT: "friendly_units_with_trait",
  TARGET_FRIENDLY_UNIT_WITH_TRAIT: "friendly_unit_with_trait",
  TARGET_RANDOM_HAND_UNIT_WITH_TRAIT: "random_hand_unit_with_trait",
  TARGET_FRIENDLY_DAMAGE_SPELLS: "friendly_damage_spells",
  TARGET_FRIENDLY_SPELLS_IN_HAND: "friendly_spells_in_hand",
  TARGET_FRIENDLY_CARDS_IN_HAND_WITH_TRAIT: "friendly_cards_in_hand_with_trait"
};

module.exports = C;
